# Introduction

Understanding the patterns, causes, and consequences of recruitment variability in marine systems is one of the primary goals among marine ecologists (Hjort 1914, Fogarty et al. 1991, Pepin 1991, Caley et al. 1996, Sutherland et al. 2013, Johnson et al. 2014). Many marine organisms have stage-structured life cycles with a distinct larval and adult stage (Thorson 1950). Mortality rates are extremely high during the larval stage (McGurk 1986, Rumrill 1990, Gosselin and Qian 1997), and even small variations in these rates can drive large fluctuations in the abundance of individuals surviving to adulthood (Houde and Hoyt 1987). While many early studies have focused on how larval abundance may regulate recruitment through density-dependent processes (Hjort 1914, Roughgarden et al. 1988, Jones 1990, Murdoch 1994, Caley et al. 1996), there has been a growing appreciation for how the phenotypic composition of a population may affect population dynamics (Gaillard et al. 2000, Schoener 2011). Marine species with planktonic larval stages have the potential to undertake long distance dispersal (Thorson 1950), and encountering novel environments during this dispersal may cause phenotypic plasticity in individuals (Agrawal 2001). However, understanding how phenotype distributions can explicitly drive changes in population dynamics remains a difficult task (Saccheri and Hanski 2006). Thorough understandings of phenotype distributions in both larval and adult populations, and the fitness benefits of these phenotypes, are essential for understanding population dynamics (Johnson et al. 2014).  

## Drivers of recruitment

Recruitment dynamics are fundamentally driven by the supply of larvae, both in quantity and quality, which in turn depends on dispersal (Roughgarden et al. 1988, Fogarty et al. 1991, Caley et al. 1996, Cowen and Sponaugle 2009). The processes affecting dispersal can be broadly categorised into physical processes and biological traits (Largier 2003, Pineda et al. 2007). Coastal environments can experience strong interactions between topography, water columns, tidal forces, and wind (Largier 2003), variations in which may either promote long distance dispersal or high rates of retention. Landscape features like eddies (Sponaugle et al. 2005), heterogeneous bottom topography (Largier 2003), and frontal convergences (Graham and Largier 1997) will likely restrict access to offshore currents and limit dispersal. Furthermore, larvae can disperse through active or passive means. Many invertebrates and plants are likely to be passive dispersers, whereas fish may more commonly have actively swimming larvae (Cowen 2002, Leis 2006). Regardless of mechanism, dispersal will determine which environments individuals will encounter (Cowen and Sponaugle 2009, Pfaff et al. 2015), and these environments may then affect the survival and phenotype of individuals (Jonsson 1985, Kerr and Secor 2009). Phenotypic traits are known to vary extensively among individuals (Cushing 1975, Jenkins and King 2006, Shima and Swearer 2009), and these traits may be sensitive to surrounding conditions (Houde and Zastrow 1993). 

Genetics will obviously play a considerable role in the quality of individuals, as will pre-hatch factors such as parental condition (McCormick 2006), and reproductive timing (Cargnelli and Gross 1996). However, many marine species display substantial phenotypic plasticity in response to environmental factors. Current paradigms suggest that dispersal pathways may change stochastically in time and space (Siegel et al. 2003, Woodson and McManus 2007), so therefore these pathways will determine what environments will be encountered (Cowen and Sponaugle 2009). Phenotype can determine the quality of an individual, and therefore its rearing environment can have substantial impacts on success (Pepin 1991, Shima and Swearer 2009). While many phenotypic traits can be environmentally influenced, growth and size are among the most responsive and most studied (Anderson 1988, Litvak and Leggett 1992, Meekan et al. 2003, Sponaugle and Pinkard 2004, Phillips 2005, Sponaugle et al. 2006, Fiksen et al. 2007). Growth is often correlated with condition, and therefore growth has been used as a proxy to infer fish quality (Bolger and Connolly 1989, Rätz and Lloret 2003, Shima and Swearer 2009). Early work supported the ‘bigger is better’ hypothesis, suggesting that larger, faster growing individuals are less susceptible to size-selective mortality (Oliver et al. 1979, Post and Prankevicius 1987, Miller et al. 1988, Tsukamoto et al. 1989, Cargnelli and Gross 1996). The growth-mortality framework of Anderson (1988) provided three conceptual mechanisms for the relationship between growth and mortality. First, if mortality is a function of size, then larger individuals of equal age will experience lower rates of mortality (Leggett and Deblois 1994). Second, if mortality is inversely related to size, then faster growing individuals will have lower mortality rates as they spend less time at vulnerable sizes (Ware 1975). Third, if mortality is dependent on ontogeny, and juveniles have lower mortality rates than larvae, then individuals that develop the fastest and transition from larvae to juvenile earliest will experience the lowest mortality (Chambers and Leggett 1987). However, subsequent studies have found either a lack of, or contradictory support for faster growth being beneficial for survival (Amara et al. 1994, Good et al. 2001, Munch et al. 2003, Holmes and McCormick 2006). Predators were also proposed to be the mechanism regulating the growth-mortality hypothesis through size selective mortality (Bailey and Houde 1989), and predation is thought to be the dominant regulating mechanism especially in freshwater systems (Werner et al. 1977, Tonn and Paszkowski 1986, Savino and Stein 1989). However, contrary to the ‘bigger is better’ hypothesis, predators have been shown to select larger prey due to their increased visibility (Litvak and Leggett 1992). There remains substantial evidence that growth and phenotype have significant effects on individual success, but the direction and context may be system dependent.

Dispersal typically occurs during the larval stage, and is completed when larvae metamorphose into the adult form at settlement. However, pelagic species may also disperse as juveniles or adults (Cowen and Sponaugle 2009). In particular, migratory species often disperse in their metamorphosed form, meaning they must adopt life history strategies to survive in a range of environments. Timing of migration movements can coincide with ontogenetic shifts, and evidence suggests that selective processes may change with ontogeny (Meekan et al. 2006, Gagliano et al. 2007). Studies on reef fish indicate that selective processes often favour fish that settle young and grow fast (Grorud-Colvert and Sponaugle 2011). However, selective pressures may change with settlement, ontogeny, and habitat, and high condition in one life stage may not be an indicator of success in later life stages (Johnson and Hixon 2010). Carry-over effects (i.e., effects of early life history on subsequent life stages), have been documented throughout the animal kingdom (amphibians: Smith 1987, Berven 1990, Scott 1994, insects: Taylor et al. 1998, marine invertebrates: Crean et al. 2011, birds: Norris 2005, Sorensen et al. 2009, and fish: Ward and Slaney 1988, Shima and Findlay 2002, Gagliano et al. 2007, Grorud-Colvert and Sponaugle 2011). Carry-over effects can be widespread in fish due to the prevalence of migratory species that will naturally develop in different habitats over their life cycle. In particular, species with diadromous life cycles, such as amphidromy, make excellent model systems for studying these effects, as many amphidromous fish will develop into juveniles in saltwater, and then into adults in freshwater.
Amphidromy is distinct from its sister categories, anadromy and catadromy, due to the migration across biomes being trophic rather than gametic (McDowall 2007). Whereas anadromous and catadromous fish cross the marine/freshwater biome as reproductively mature adults and immediately undertake spawning (Myers 1949), amphidromous fish continue to develop into adults after migration and will spawn after undertaking further development in freshwater (McDowall 2007). Undertaking diadromous migrations is energetically costly, however the primary benefit appears to be exploiting the food rich marine environment (Gross et al. 1988, Edeline 2007). Food availability in oceans is known to vary with temperature, upwelling, and nutrient supply (Bunt 1975), and there is evidence that migration patterns appear to follow food supply (Gross et al. 1988). Food and temperature are known to be the primary determinants of growth rate (Houde and Zastrow 1993), so fish phenotypes are likely to vary during migration as they experience different environmental factors (Schluter et al. 1991, Searcy and Sponaugle 2001, Gagliano et al. 2007, Johnson and Hixon 2010). For species with migratory life cycles, phenotypes conferring high larval fitness may become disadvantageous in the juvenile or adult stages due to new challenges posed by a novel environment. 

Fish present an excellent system for studying phenotypic plasticity, carry-over effects, and recruitment dynamics, due to a daily record of their growth history being recorded in their otoliths (small calcium carbonate structures that are found in the inner ear; Campana and Neilson 1985). Otoliths form by regular accumulation of growth rings, which can be used to infer growth history, determine age (Pannella 1971), and identify major events in an individual’s life history (Victor 1982). A variety of hard structures have been used for seasonal growth validation, including vertebrae (Brown and Gruber 1988), opercula (Baker and Timmons 1991), scales (Robillard and Marsden 1996), and fin rays (Cass and Beamish 1983). However, the use of otoliths is the most commonly applied method and allows accurate reconstructions of recruitment patterns (Casselman 1987, Wilson and McCormick 1997). Measuring the distance between successive rings can be used to estimate daily somatic growth (Campana and Neilson 1985). While otoliths provide a powerful analytical tool, they must be treated with caution. Abrupt and intense physiological changes may decouple the relationship between otolith growth and somatic growth (Francis et al. 1993, Hoey and McCormick 2004, Baumann et al. 2005, Baumann and Gagliano 2011). This can often occur at settlement, meaning that post-settlement otolith rings may not be a reliable indicator of growth (Hoey and McCormick 2004). Thus, interpretations of otolith growth and somatic growth must include an understanding of the life history and ecological context of the species of interest.

While the formation of rings is influenced by physical processes, a critical step in the accurate aging of fish is the validation of rings forming in a regular pattern. This has been done for a considerable number of species (Taubert and Coble 1977, Fowler and Doherty 1992, Stewart et al. 1995, Newman et al. 1996, Vigliola 1997, Cappo et al. 2000, Vilizzi and Copp 2013, Peel et al. 2016, Taylor et al. 2016), and for the focal species of this thesis, Galaxias maculatus (McDowall et al. 1994). 
 
## Study species

The geographically widespread fish Galaxias maculatus provides an excellent study species for observational evaluations of recruitment dynamics. G. maculatus is an amphidromous fish that is found throughout New Zealand, Australia, and South America (McDowall 1978, Berra et al. 1996, Cussac et al. 2004). Adult G. maculatus lay their eggs amongst submerged vegetation during high spring tides (McDowall and Charteris 2006). Eggs are exposed to the air as the tide recedes and develop in this moist environment for approximately two weeks, before hatching with the next spring tide and dispersing into the marine environment (Benzie 1968a). Larvae will spend three to six months developing in the marine environment before migrating back to freshwater streams as metamorphosed juveniles (McDowall et al. 1994). The majority of these migrations take place from August to November (McDowall and Eldon 1980). Juvenile fish settle further up the river and develop into reproductively mature adults over the ensuing six months (Cussac et al. 1992). Mature adults move downstream to spawn in estuaries, and will typically die following spawning (Benzie 1968a). During this thesis I will be discussing recruitment at several life stages, both in the traditional sense of juvenile fish being added to the adult population (Fogarty et al. 1991), and in the sense of migrating juveniles entering the freshwater river. At migration, when juvenile fish enter a freshwater stream they can be considered ‘recruiting’ to the stream. Therefore, juveniles caught at the river mouth will be referred to in this thesis as ‘recruits’.

G. maculatus individuals show very high phenotypic plasticity (Barriga et al. 2012). Studies have validated plastic responses to changes in temperature, food availability, and predation risk. Food rich environments promote deeper bodies with shorter caudal peduncles, and vice versa in food limited environments (Kekalainen et al. 2010). Body size can also change in response to predation risk, favouring streamlined shapes that promote efficient swimming (Milano et al. 2006). Furthermore, both the migrating juveniles and the spawning adults can be easily caught, which facilitates identification of shifts in phenotypic distributions across life stages. 


## Thesis research

This thesis has three primary aims: (1) to characterise the extent of phenotypic variability at recruitment in early life history traits of G. maculatus, (2) to estimate mortality rates for spatially and temporally discrete cohorts of juvenile G. maculatus, and (3) to determine the effect of early life history traits on future success. In Chapter 2, I compare phenotypes of recruiting G. maculatus, both spatially across sites and temporally within sites. In Chapter 3, I estimate mortality rates for cohorts of recruits and assess whether these mortality rates vary as a function of larval quality. In Chapter 4, I quantify the early life history traits of adult fish to determine whether specific phenotypes show higher success than others. In Chapter 5, I synthesise the results from the previous three chapters and discuss hypotheses generated from these studies. This thesis represents a longitudinal study that investigates G. maculatus recruitment at three distinct life stages, and thus it represents one of the few studies that takes a holistic view of recruitment across the entire life cycle. By considering the entire life history, I provide a more complete understanding of recruitment in an amphidromous fish; a complex and difficult dynamic rate function to understand.

I have prepared the following data chapters in the form of independent manuscripts to facilitate submission to peer-reviewed journals. Therefore, each data chapter has its own Introduction and Discussion section, and consequently, there is some repetition across chapters. 
