# Discussion

## Summary

The primary aim of this thesis was to investigate how recruitment of the amphidromous fish Galaxias maculatus varied across both spatial and temporal scales, and the demographic consequences of this variation. New Zealand has been a place of extensive research on G. maculatus, and Galaxiids in general (Benzie 1968a, McDowall 1969, McDowall 1972, McDowall et al. 1994, Hickford et al. 2010, Hickford and Schiel 2013). Four of the five native Galaxiid species are currently threatened, and this fishery is recognised as being socially, culturally, and economically important to New Zealand (McDowall 1968, McDowall 1984, Rowe et al. 1999). Therefore, studies pertaining to recruitment dynamics of native Galaxiid fish are important for understanding how conservation and management plans can be structured for the long term preservation of these species. 

This thesis concluded that 1) significant phenotypic variation can arise in populations that recruit in close spatial (20 km) and temporal (one day) proximity, 2) that mortality rates are, at best, weakly related to larval quality, and 3) that adult freshwater populations of G. maculatus may be partially shaped by growth rates experienced at sea, and hatch dates. My results have revealed the importance of considering subtle (and putatively minor) spatial and temporal differences in the context of recruitment patterns, and ignoring these differences could lead to poor interpretations and decisions. In addition, this work shows further support for the idea that early life history can influence and predict measures of adult survival. This thesis raises new questions, primarily around the potential of local retention in harbour systems, the extent to which recruitment can vary over seemingly small and insignificant spatial and temporal scales, and of optimal growth strategies in the post-settlement phase. 


## Landscape features and dispersal potential

Considerable research effort on G. maculatus has focussed on determining the extent of natal homing (Barker and Lambert 1988, Waters et al. 2000, Hickford and Schiel 2016), with recent genetic and otolith studies suggesting that G. maculatus shows very little homing. Mitochondrial DNA results from Waters et al (2000) suggests that G. maculatus show very little population structure, due to the extent of gene flow during marine dispersal. Similarly, otolith microchemistry results from Hickford and Schiel (2016) suggest that less than three percent of individuals return to their natal stream. However, there is also evidence that G. maculatus larvae hatched on the east coast of New Zealand will typically return to east coast rivers, and vice versa (Hickford and Schiel 2016). Therefore, it seems unlikely that G. maculatus larvae will regularly cross from the east to west coasts of New Zealand, and there may be physical barriers (i.e. water currents) that prevent this level of dispersal (Chiswell and Rickard 2011). 

Despite this apparent high level of larval mixing and low level of natal return, one hypothesis I have proposed to explain my results throughout this thesis is that the Hutt River shows an uncharacteristically high level of philopatry, primarily due to the physical retentive properties of the Wellington Harbour. There is extensive evidence that harbour systems can promote retention of larvae by virtue of circulating currents (Jessopp and McAllen 2007, Shima and Swearer 2009, Morgan et al. 2011), and Wellington Harbour specifically has been suggested to promote retention of fish larvae (Swearer and Shima 2010). Furthermore, Wellington Harbour may act as a ‘nursery’ ground, as it is nutrient rich, supports high standing stocks of plankton (Helson et al. 2007), and stays at optimal temperatures for G. maculatus growth (Maxwell 1956, Mitchell 1989, Richardson et al. 1994). Nursery habitats are known to retain and attract larvae (Caputi et al. 1996, Condie et al. 2011, Beldade et al. 2016), and larvae are less likely to disperse far when local conditions present a favourable and productive environment (Swearer et al. 1999). Theoretically, Wellington Harbour appears to show the characteristics of a retentive system, however this thesis has not been a study of local retention and natal homing. While I can speculate on the retentive properties of Wellington Harbour, this is a hypothesis that needs to be empirically validated, and I discuss experimental suggestions for this validation below. 

## Variation in recruitment over spatial scales

The hypothesis of retention in harbour systems is closely linked with my overall result that recruitment patterns vary over small spatial scales. The explanations I have suggested above (i.e., water currents affecting dispersal) may also play a strong role in driving the observed difference between the juvenile fish entering the Hutt River compared to the Wainuiomata River. The processes of recruitment are fundamentally influenced by the availability of larvae (Gaines et al. 1985, Victor 1986, Milicich et al. 1992), and spatial variability in recruitment will often arise from spatial differences in larval availability (Koslow et al. 1987, Mann 1993). Larvae may drift passively with strong currents (Williams et al. 1984, Cowen and Castro 1994, Weber et al. 2015), become aggregated into higher densities by internal waves (Kingsford and Choat 1986, Shanks and Wright 1987, Greer et al. 2014), or be locally retained by eddies (Mullaney and Suthers 2013, Beldade et al. 2016). Therefore, these strong site-specific recruitment patterns may be driven by different hydrodynamic processes acting on each river (Maxwell 1956, Bowman et al. 1983). This has implications for studies of G. maculatus recruitment, as it may prove difficult to make generalisations about recruitment patterns without careful review of geographic position and current influenced dispersal. 

Spatial variation in phenotype patterns and larval retention can have strong ecological consequences. Sites that have low levels of retention may be considered demographically open, and become source populations for other areas in a metapopulation (Jones et al. 2009). This is a common pattern in amphidromous species due to their high dispersal capabilities (McDowall 2007, McDowall 2010), but may lead to externally regulated extinction balances. If a population does not self-recruit then it is susceptible to high rates of local extinction due to demographic stochasticity (Jones et al. 2009). However, other open populations can then balance this local extinction through demographic connectivity, and thus can show resilience over evolutionary time scales (Kritzer and Sale 2006, McDowall 2010). Conversely, having high levels of retention may lead to a population being demographically closed. Closed populations can be regulated by either density-independent or –dependent effects, which can have differing population consequences. Closed populations regulated by density-dependent processes show low susceptibility to local extinction and are able to persist through self recruitment, yet have no way to be re-established following extinction (Jones et al. 2009). Closed populations regulated by density-independent processes have no internal regulation (Hixon et al. 2002), and therefore are unlikely to recover following local extinction (Gonzalez et al. 1998, Hill et al. 2002). This metapopulation framework sets up an interesting dynamic with the closely situated harbour-coast system. Under the assumption that Wellington Harbour is a partially closed population, and Cook Strait is primarily an open population, then the persistence of the Wellington Harbour population may be dependent on how much input it has from other systems. If Wellington Harbour was to experience local extinction, then its recolonization may depend on closely situated open populations like the Wainuiomata River. 


## Effects of river mouth closure

Migratory species can be classified as either obligate or facultative, depending on whether their migration is a necessary step in completing their life cycle (McDowall 1988, McDowall 1995). G. maculatus are generally considered to be obligate migrants (McDowall 1995), despite the presence of viable landlocked populations (Battini et al. 2000, Barriga et al. 2002, Barriga et al. 2007). These landlocked populations still undertake migrations, with newly hatched larvae moving from spawning locations in streams to the limnetic zone of lakes (Pollard 1971). This obligatory migration can make amphidromous populations of G. maculatus susceptible to the effects of river mouth closure. During November 2015 the Wainuiomata River mouth was closed by gravel build-up, and therefore juvenile G. maculatus were blocked from entering the river. It is unknown whether closure of the Wainuiomata River mouth is a common occurrence, but frequent closures may drive temporally variable patterns in recruitment. My results from Chapter 2 showed that growth rates decreased over the recruitment season, such that the Hutt River’s slowest growing monthly cohort of fish came from November. In Chapter 4, I found that adult G. maculatus growth rates were overall very slow, and that they matched juvenile growth rates from October in the Wainuiomata River and November in the Hutt River. Chapter 4 also indicated that there may be an ‘optimum’ time to hatch, but this may not benefit freshwater survival if fish are unable to enter the river. This may lead to interesting metapopulation dynamics, where phenotypically ‘superior’ fish are unable to enter a freshwater habitat to settle. G. maculatus juveniles may be forced to undertake further dispersal to find a new river to enter. This may enhance demographic connectivity between rivers, but may also increase temporal fluctuations in recruitment, depending on the rivers susceptibility to closure (McDowall 1995). Therefore, no fish entering the Wainuiomata River in November may have affected patterns of adult recruitment, both in the Wainuiomata River and geographically proximate rivers


## Future directions

A central hypothesis I have proposed in this thesis is that Wellington Harbour promotes a higher retention of larval G. maculatus (that likely have hatched in the Hutt River) than would be expected in a coastally positioned system. Waters et al (2000) used the mitochondrial CO1 gene to conclude that there was no genetic population structure in New Zealand. However the small number of migrants required to overcome genetic differentiation may mask any evidence of short term isolation. Therefore, a result of no population structure may be an artefact of a small amount of mixing between harbour and coastal populations (Slatkin 1985). With this limitation, a more powerful approach may be to generate whole genome data in the form of SNPs (single nucleotide polymorphisms). Next generation techniques such as RAD sequencing (Baird et al. 2008) and Genotyping-by-Sequencing (Elshire et al. 2011) would provide the fine scale genetic data needed to detect whether harbour populations experience higher retention of larval G. maculatus than typical coast populations. 

Results from Chapter 4 show that there was a correlation between juveniles that had experienced slow marine growth during early life stages, and the early life growth rate of adult fish. While there is support in the literature for slow growth rates enhancing fitness (Litvak and Leggett 1992), an experimental setup is required to elucidate that slower growth rates are indeed a dominant factor in the recruitment process for G. maculatus. Mesocosms have been successfully used to test selective mortality on phenotypic traits (Parker 1971, Hargreaves and LeBrasseur 1986, Caie 2016), and a similar approach may be appropriate here, where a mesocosm is constructed that contains juvenile G. maculatus and a natural predator (i.e., trout). A comparison of the otoliths of consumed fish (from predator guts) and unconsumed fish would facilitate conclusions about selective mortality on growth rates, and whether slow growth is an optimum strategy for post-settlement G. maculatus. 

Chapters 2, 3, and 4 all made use of a dataset collected over a single year of sampling. Although I was able to describe both spatial and temporal patterns in my data, it is difficult to know whether these patterns are consistent over multiple years. Similar studies by McDowall (1994) and Barbee et al (2011) found results only weakly related to the age and growth data presented in this thesis, which suggests that these patterns might experience considerable annual fluctuations. Future studies should try to accommodate multi-year sampling of juvenile and adult G. maculatus in order to compare year-to-year phenotype distributions and shifts.  

## Conclusions

In summary, populations of fish are comprised of individuals with diverse early life histories and phenotypes. This diversity of life histories can have implications for survival in both pre- and post-settlement life stages, and is crucial for shaping the demographic rates of populations. This thesis contributes to the knowledge that early life history has carry over effects to future life stages, and recruitment is dependent on smaller spatial and temporal scales than previously thought. Therefore, context and life history should be understood when describing the ecology of any organism, especially those with stage structured life histories.
